# Gitpod configuration for Android development
image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-browser
  - port: 3001
    onOpen: ignore

tasks:
  - name: Setup Android Development
    init: |
      # Install Android SDK
      wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
      unzip commandlinetools-linux-8512546_latest.zip
      mkdir -p $HOME/android-sdk/cmdline-tools
      mv cmdline-tools $HOME/android-sdk/cmdline-tools/latest
      
      # Set environment variables
      export ANDROID_HOME=$HOME/android-sdk
      export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
      
      # Accept licenses and install required packages
      yes | sdkmanager --licenses
      sdkmanager "platforms;android-33" "build-tools;33.0.0" "platform-tools"
      
      # Install dependencies
      npm install
    command: |
      export ANDROID_HOME=$HOME/android-sdk
      export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
      npm run dev

  - name: Mobile Development
    command: |
      export ANDROID_HOME=$HOME/android-sdk
      export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
      echo "🚀 Android development environment ready!"
      echo "📱 Run 'npm run mobile:build' to build for Android"
      echo "🔧 Run 'npx cap run android' to build APK"

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - esbenp.prettier-vscode
    - ms-vscode.vscode-typescript-next